### ISSUE TITLE
[CLOSED] Allow multiple categories for administrative appeals tribunal decisions

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#671]
<a href="https://github.com/robmckinnon"><img src="https://avatars.githubusercontent.com/u/3447?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robmckinnon](https://github.com/robmckinnon)**
_Thursday 03 March 2016 at 14:53 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/pull/671_

---

Domain experts want to be able to set multiple tribunal decision categories and sub-categories for administrative appeals tribunal decisions.

Rename `tribunal_decision_category` to `tribunal_decision_categories`.

Rename `tribunal_decision_sub_category` to `tribunal_decision_sub_categories`.

**Requires this rummager PR is merged also: https://github.com/alphagov/rummager/pull/587**

---

_**[robmckinnon](https://github.com/robmckinnon)** included the following code: https://github.com/alphagov/specialist-publisher/pull/671/commits_

**Comment by benilovj** [comment]
<a href="https://github.com/h-lame"><img src="https://avatars.githubusercontent.com/u/608?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [h-lame](https://github.com/h-lame)**
_Thursday 17 March 2016 at 15:32 GMT_

---

@robmckinnon - I think you're probably correct wrt the rename.  `category_names` is more correct, but `categories_name` is more consistent.  In theory happy to merge this, but there are failing tests.  Not sure if you can see our jenkins so I'm pasting them in below:

```
(::) failed steps (::)

#<RummagerHelpers::FakeRummager:0x007f4d182c4568> received :add_document with unexpected arguments
  expected: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", hash_including(:title=>"Example UTAAC decision", :tribunal_decision_category=>"benefits-for-children", :tribunal_decision_category_name=>"Benefits for children", :tribunal_decision_sub_category=>"benefits-for-children-child-benefit", :tribunal_decision_sub_category_name=>"Benefits for children - child benefit", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_decision_date=>"2015-02-02", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo."))
       got: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", {:title=>"Example UTAAC decision", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.", :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision", :indexable_content=>"## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:", :organisations=>["upper-tribunal-administrative-appeals-chamber"], :public_timestamp=>Thu, 17 Mar 2016 15:29:28 +0000, :tribunal_decision_categories=>["benefits-for-children"], :tribunal_decision_categories_name=>["Benefits for children"], :tribunal_decision_decision_date=>"2015-02-02", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"], :tribunal_decision_sub_categories_name=>["Benefits for children - child benefit"]})
Diff:
@@ -1,4 +1,18 @@
 ["utaac_decision",
  "/administrative-appeals-tribunal-decisions/example-utaac-decision",
- "hash_including(:title=>\"Example UTAAC decision\", :tribunal_decision_category=>\"benefits-for-children\", :tribunal_decision_category_name=>\"Benefits for children\", :tribunal_decision_sub_category=>\"benefits-for-children-child-benefit\", :tribunal_decision_sub_category_name=>\"Benefits for children - child benefit\", :tribunal_decision_judges=>[\"angus-r\"], :tribunal_decision_judges_name=>[\"Angus, R\"], :tribunal_decision_decision_date=>\"2015-02-02\", :description=>\"Nullam quis risus eget urna mollis ornare vel eu leo.\")"]
+ {:title=>"Example UTAAC decision",
+  :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.",
+  :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision",
+  :indexable_content=>
+   "## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:",
+  :organisations=>["upper-tribunal-administrative-appeals-chamber"],
+  :public_timestamp=>Thu, 17 Mar 2016 15:29:28 +0000,
+  :tribunal_decision_categories=>["benefits-for-children"],
+  :tribunal_decision_categories_name=>["Benefits for children"],
+  :tribunal_decision_decision_date=>"2015-02-02",
+  :tribunal_decision_judges=>["angus-r"],
+  :tribunal_decision_judges_name=>["Angus, R"],
+  :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"],
+  :tribunal_decision_sub_categories_name=>
+   ["Benefits for children - child benefit"]}]
 (RSpec::Expectations::ExpectationNotMetError)
./features/support/document_helpers.rb:81:in `check_added_to_rummager'
./features/support/document_helpers.rb:134:in `check_document_is_published'
./features/step_definitions/utaac_support_decision_steps.rb:112:in `/^the UTAAC decision should be published$/'
features/publishing-an-utaac-decision.feature:12:in `Then the UTAAC decision should be published'

#<RummagerHelpers::FakeRummager:0x007f4d182c4568> received :add_document with unexpected arguments
  expected: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", hash_including(:title=>"Example UTAAC decision", :tribunal_decision_category=>"benefits-for-children", :tribunal_decision_category_name=>"Benefits for children", :tribunal_decision_sub_category=>"benefits-for-children-child-benefit", :tribunal_decision_sub_category_name=>"Benefits for children - child benefit", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_decision_date=>"2015-02-02", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo."))
       got: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", {:title=>"Example UTAAC decision", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.", :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision", :indexable_content=>"## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:", :organisations=>["upper-tribunal-administrative-appeals-chamber"], :public_timestamp=>Thu, 17 Mar 2016 15:29:28 +0000, :tribunal_decision_categories=>["benefits-for-children"], :tribunal_decision_categories_name=>["Benefits for children"], :tribunal_decision_decision_date=>"2015-02-02", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"], :tribunal_decision_sub_categories_name=>["Benefits for children - child benefit"]})
Diff:
@@ -1,4 +1,18 @@
 ["utaac_decision",
  "/administrative-appeals-tribunal-decisions/example-utaac-decision",
- "hash_including(:title=>\"Example UTAAC decision\", :tribunal_decision_category=>\"benefits-for-children\", :tribunal_decision_category_name=>\"Benefits for children\", :tribunal_decision_sub_category=>\"benefits-for-children-child-benefit\", :tribunal_decision_sub_category_name=>\"Benefits for children - child benefit\", :tribunal_decision_judges=>[\"angus-r\"], :tribunal_decision_judges_name=>[\"Angus, R\"], :tribunal_decision_decision_date=>\"2015-02-02\", :description=>\"Nullam quis risus eget urna mollis ornare vel eu leo.\")"]
+ {:title=>"Example UTAAC decision",
+  :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.",
+  :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision",
+  :indexable_content=>
+   "## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:",
+  :organisations=>["upper-tribunal-administrative-appeals-chamber"],
+  :public_timestamp=>Thu, 17 Mar 2016 15:29:28 +0000,
+  :tribunal_decision_categories=>["benefits-for-children"],
+  :tribunal_decision_categories_name=>["Benefits for children"],
+  :tribunal_decision_decision_date=>"2015-02-02",
+  :tribunal_decision_judges=>["angus-r"],
+  :tribunal_decision_judges_name=>["Angus, R"],
+  :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"],
+  :tribunal_decision_sub_categories_name=>
+   ["Benefits for children - child benefit"]}]
 (RSpec::Expectations::ExpectationNotMetError)
./features/support/document_helpers.rb:81:in `check_added_to_rummager'
./features/support/document_helpers.rb:134:in `check_document_is_published'
./features/step_definitions/utaac_support_decision_steps.rb:112:in `/^the UTAAC decision should be published$/'
features/publishing-an-utaac-decision.feature:16:in `Then the UTAAC decision should be published'

#<RummagerHelpers::FakeRummager:0x007f4d182c4568> received :add_document with unexpected arguments
  expected: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", hash_including(:title=>"Example UTAAC decision", :tribunal_decision_category=>"benefits-for-children", :tribunal_decision_category_name=>"Benefits for children", :tribunal_decision_sub_category=>"benefits-for-children-child-benefit", :tribunal_decision_sub_category_name=>"Benefits for children - child benefit", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_decision_date=>"2015-02-02", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo."))
       got: ("utaac_decision", "/administrative-appeals-tribunal-decisions/example-utaac-decision", {:title=>"Example UTAAC decision", :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.", :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision", :indexable_content=>"## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:", :organisations=>["upper-tribunal-administrative-appeals-chamber"], :public_timestamp=>Thu, 17 Mar 2016 15:29:31 +0000, :tribunal_decision_categories=>["benefits-for-children"], :tribunal_decision_categories_name=>["Benefits for children"], :tribunal_decision_decision_date=>"2015-02-02", :tribunal_decision_judges=>["angus-r"], :tribunal_decision_judges_name=>["Angus, R"], :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"], :tribunal_decision_sub_categories_name=>["Benefits for children - child benefit"]})
Diff:
@@ -1,4 +1,18 @@
 ["utaac_decision",
  "/administrative-appeals-tribunal-decisions/example-utaac-decision",
- "hash_including(:title=>\"Example UTAAC decision\", :tribunal_decision_category=>\"benefits-for-children\", :tribunal_decision_category_name=>\"Benefits for children\", :tribunal_decision_sub_category=>\"benefits-for-children-child-benefit\", :tribunal_decision_sub_category_name=>\"Benefits for children - child benefit\", :tribunal_decision_judges=>[\"angus-r\"], :tribunal_decision_judges_name=>[\"Angus, R\"], :tribunal_decision_decision_date=>\"2015-02-02\", :description=>\"Nullam quis risus eget urna mollis ornare vel eu leo.\")"]
+ {:title=>"Example UTAAC decision",
+  :description=>"Nullam quis risus eget urna mollis ornare vel eu leo.",
+  :link=>"/administrative-appeals-tribunal-decisions/example-utaac-decision",
+  :indexable_content=>
+   "## Header\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n\r\nPraesent commodo cursus magna, vel scelerisque nisl consectetur et.\n## Link to attachement:",
+  :organisations=>["upper-tribunal-administrative-appeals-chamber"],
+  :public_timestamp=>Thu, 17 Mar 2016 15:29:31 +0000,
+  :tribunal_decision_categories=>["benefits-for-children"],
+  :tribunal_decision_categories_name=>["Benefits for children"],
+  :tribunal_decision_decision_date=>"2015-02-02",
+  :tribunal_decision_judges=>["angus-r"],
+  :tribunal_decision_judges_name=>["Angus, R"],
+  :tribunal_decision_sub_categories=>["benefits-for-children-child-benefit"],
+  :tribunal_decision_sub_categories_name=>
+   ["Benefits for children - child benefit"]}]
 (RSpec::Expectations::ExpectationNotMetError)
./features/support/document_helpers.rb:81:in `check_added_to_rummager'
./features/support/document_helpers.rb:134:in `check_document_is_published'
./features/step_definitions/utaac_support_decision_steps.rb:112:in `/^the UTAAC decision should be published$/'
features/publishing-an-utaac-decision.feature:49:in `Then the UTAAC decision should be published'

Failing Scenarios:
cucumber -p build features/publishing-an-utaac-decision.feature:9 # Scenario: can publish a draft UTAAC decision
cucumber -p build features/publishing-an-utaac-decision.feature:14 # Scenario: can create a new UTAAC decision and publish immediately
cucumber -p build features/publishing-an-utaac-decision.feature:47 # Scenario: Minor updates do not send emails or update logs

274 scenarios (3 failed, 271 passed)
1398 steps (3 failed, 8 skipped, 1387 passed)
2m25.970s
```

**Comment by benilovj** [comment]
<a href="https://github.com/robmckinnon"><img src="https://avatars.githubusercontent.com/u/3447?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [robmckinnon](https://github.com/robmckinnon)**
_Friday 18 March 2016 at 10:33 GMT_

---

@h-lame I've fixed the failing cucumber. I can rebase again if https://github.com/alphagov/specialist-publisher/pull/673 is merged first.

**Comment by benilovj** [comment]
<a href="https://github.com/h-lame"><img src="https://avatars.githubusercontent.com/u/608?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [h-lame](https://github.com/h-lame)**
_Friday 18 March 2016 at 15:20 GMT_

---

This looks good.  Thanks for incorporating those changes @robmckinnon.
